- LICENSE
- README.md
- align.js
- cli.js
- colorize.js
- combine.js
- format.js
- index.js
- json.js
- label.js
- levels.js
- logstash.js
- package.json
- pad-levels.js
- pretty-print.js
- printf.js
- simple.js
- splat.js
- test/format.test.js
- timestamp.js
- uncolorize.js
> Related to: https://github.com/winstonjs/winston/pull/1083
Not enough test coverage yet, but there is significant coverage in the upstream `winston#3.x` tests. Follow-up PR will address the coverage numbers.
> All existing winston@2 formats. Finished README.md

- README.md
${message} isn't valid syntax. Changed to ${info.message} since it seems that the info object was just forgotten.
> Fix broken example code.

- package.json
- test/timestamp.test.js
- timestamp.js
This PR solves the same issue as #6 (#4), but it also:
- Adds test cases `./test/timestamp.test.js`
- Replaces `date-fns` with [`fecha`](https://github.com/taylorhakes/fecha) to reduce install size, about ~3.8 MB (see pictures)
**`date-fns`:**
**`fecha`:**
> Fix timestamp and replace date-fns with fecha (with test cases)

- index.d.ts
Once these are merged and published in an updated version, we can remove the logform typings from DefinitelyTyped.
> Add Typescript typings (ported from DefinitelyTyped)

- simple.js
- test/simple.test.js
- test/uncolorize.test.js
This PR aims to improving logging using simple format. As a default behavior, logs look like:
```text
info: whatever {}
```
where `{}` shows that there is no other information to display. In such a case, logs should look like:
```text
info: whatever
```
On the other hand, custom info must be printed if exists:
```text
info: whatever {"rest":"something"}
```
> Remove unnecessary message

- index.d.ts
- index.js
- ms.js
- package-lock.json
- package.json
- test/ms.test.js
This should fix #20, it adds a `ms` property to the `info` object. The value of the `ms` property is the difference between two calls of the function. To implement this feature I looked how it was done by the `debug` module also mentioned in #20, so this PR also adds a new dependency on [`ms`](https://www.npmjs.com/package/ms). Tests are also added for this PR in `test/ms.test.js`.
I also updated the `index.d.js` file for the TypeScript definitions. I've never worked with TypeScript so I hope it is correct.
> Add ms format to support '+N ms' format.

- examples/padLevels.js
- pad-levels.js
- simple.js
- test/pad-levels.test.js
This PR implements the `padLevels` format. An example on how to use this format is in the `examples/` folder and the `simple` format was updated to work with he `padLevels` format. And of course tests :+1: .
>  [feat] Implement padLevels format

- json.js
- logstash.js
- package-lock.json
- package.json
- simple.js
- test/helpers.js
- test/json.test.js
While catching up with @davidmarkclements at JSConf I was reminding that `fast-safe-stringify` is a great piece of code we should use by default. This PR:
I tip my hat to @davidmarkclements here for doing all the heavy lifting:
**Before**
```
==========
OBJECT benchmark averages
BunyanObj average: 706.089ms
WinstonObj average: 519.757ms
BoleObj average: 291.980ms
LogLevelObject average: 556.841ms
PinoObj average: 279.025ms
PinoUnsafeObj average: 277.313ms
PinoExtremeObj average: 154.406ms
PinoUnsafeExtremeObj average: 151.695ms
==========
```
**After**
```
==========
OBJECT benchmark averages
BunyanObj average: 727.584ms
WinstonObj average: 446.947ms
BoleObj average: 309.041ms
LogLevelObject average: 577.650ms
PinoObj average: 282.819ms
PinoUnsafeObj average: 282.245ms
PinoExtremeObj …
```
> Use fast-safe-stringify for perf and to support circular refs

- splat.js
- test/splat.test.js
Ensures that from a performance perspective folks only get splat interpolation if they turn it on.
> Migrate functionality from winston Logger to splat format.

- cli.js
- colorize.js
- combine.js
- pad-levels.js
- test/cli.test.js
- test/colorize.test.js
- test/combine.test.js
- test/pad-levels.test.js
- test/uncolorize.test.js
> Fixes #36.
This PR does the following:
> Match expectations from `winston@2.x` for padLevels. Use that for proper CLI format

- splat.js
I'm trying to upgrade to Winston 3, but hit a snag because we're logging some database statements that contain `%s` in some cases.
Here's a very reduced example:
```js
const winston = require('winston');
const logger = winston.createLogger({
format: winston.format.combine(
winston.format.colorize(),
winston.format.splat(),
winston.format.simple(),
winston.format.printf(({level, message}) => `${level}: ${message}`)
),
transports: [
new winston.transports.Console()
]
});
logger.info('foo %s');
```
Breaks with:
```
TypeError: Cannot read property 'length' of undefined
at Splatter._splat (/myproject/node_modules/logform/splat.js:55:46)
at Splatter.transform (/myproject/node_modules/logform/splat.js:93:19)
at Format.info [as transform] (/myproject/node_modules/logform/combine.js:20:24)
at …
```
> splat formatter: Don't break when there are % placeholders but no values

- package.json
Typings were not being included with the published package.
> Include types in in package

- pretty-print.js
The most elegant way to do this seems to involve a clone of `info`, which is potentially another performance hit.  But Node.js docs already clearly say to not rely on util.inspect for production, so as long as we echo that for `prettyPrint`, I'm ok with this.
> Strip info[LEVEL] in prettyPrint; fixes #31

- splat.js
- test/splat.test.js
I can no longer log a single object as a splat:
`logger.info('hey %O', obj);`
doesn't format the splat right anymore...
But I also want this to work:
```js
const winston = require('winston');
let transports = {
console: new winston.transports.Console({level: 'info'})
};
let {format} = winston;
let logger = winston.createLogger({
format: format.combine(
format.splat(),
format.printf(info => `[${info.label}]: ${info.message}`)
),
transports: [transports.console]
});
logger.log(
'info',
'let\'s %s some %s',
'interpolate',
'splat parameters',
{label: 'label!'},
);
// [label!]: let's interpolate some splat parameters
```
This PR and an associated one in winston make both of these cases work, but @indexzero would be good if you could opine.  IIRC in 3.x we shouldn't be assigning to info.meta …
> Try better fix for #1485

- README.md
- errors.js
- index.d.ts
- index.js
- test/errors.test.js
In winston@2 you used to be able to easily log errors like this: `failingPromise().catch(logger.error)`.
Now, a little object copy prevents that from happening at the transform level: https://github.com/winstonjs/winston-transport/blob/master/index.js#L90
I'm willing to completely re-write what I did if the team thinks that this needs extra features or any changes in general, but I really believe that `logform` should come with a built-in formatter that allows developers to pass in errors to their logger.
(happy to change file names etc too).
> Add error normalizing

- json.js
The native bigint type has been available in major browsers and NodeJS for some time now however JSON.stringify requires a custom replacer or it will throw
> Add replacer for bigint on json formatter

- README.md
- json.js
The *JSON* formatter doesn't stringify objects' attributes in a consistent order by default, which is annoying when reading them.
Now we accept a new parameter for that formatter, ***stable***, which when true results in using the *fast-safe-stringify.stableStringify* function, that stringifies attributes in alphabetical order.
*README* has been updated as well.
Closes #90
> Add option for stable stringifying to JSON (#90)

- browser.js
Currently both `errors` and `ms` are not exported when used with browsers, this PR fixes that and makes it possible to use those functions in the browser. I checked, that this is working for my project.
Closes https://github.com/winstonjs/logform/issues/97 and https://github.com/winstonjs/winston/issues/1724.
> Fix errors and ms export for browsers

- errors.js
- test/errors.test.js
Sometimes a library might create a `new Error()` then set its `message` property afterwards. This will make the `message` property enumerable. If you log this through the errors() formatter, you will end up seeing the message 'undefined' because of the way it tries to extract properties from the error object and assumes that 'message' will not be one of them.
> errors formatter doesn't work if the “message” property is enumerable

- README.md
- json.js
- logstash.js
- package-lock.json
- package.json
- simple.js
- test/json.test.js
- test/logstash.test.js
Reasons for replacements:
1. It's faster (https://github.com/BridgeAR/safe-stable-stringify#performance--benchmarks)
2. It has less bugs (i also met same bug - https://github.com/davidmarkclements/fast-safe-stringify/issues/46)
From internal tests "safe-stable-stringify" is working faster and still produces correct output.
Only single *disadvantage* - you can't have randomness in property order, it's always **stable**.
> Replace JSON stringify library "fast-safe-stringify" by "safe-stable-stringify"

- index.js
This PR is very similar to #113 but retains the lazy-load behavior per @evanw's comment.
This change would enable usage of esbuild and other single-file build processes.
> fix: avoid dynamic requires

- package.json
related to [PR in Winston](https://github.com/winstonjs/winston/pull/2008/files),
This PR pins colors to 1.4.0 (which respects the previous semver range in ^1.2.0) to mitigate an identified security vulnerability in `colors@1.4.4` and `colors@1.4.44-liberty`)
@DABH , when you have a moment, would you kindly review?
> Pin colors package to 1.4.0 due to Security Vuln

- cli.js
This fixes https://github.com/winstonjs/winston/issues/2053
> In CliFormat use cli levels (not npm levels).

- index.d.ts
- json.js
- test/json.test.js
https://github.com/BridgeAR/safe-stable-stringify/releases
- Allow `opts` to configure the lib.
- Update types for new opts.
- Add tests to fill in coverage for json.js.
NB. The `Buffer.toString('base64')` conversion was removed. Buffer implements `toJSON` so this block of code was not being executed anyway, as the replacer is called with the result of `toJSON`. Base64 was never being returned.
https://nodejs.org/api/buffer.html#buftojson
> Make use of new safe-stable-stringify 2.x features 

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This implements issue templates for this repository that are mostly replicas from `WinstonJS/Winston`
> Feature: Implement issue templates

- errors.js
- test/errors.test.js
This would extend the options (currently {stack: Boolean}) to include a "cause" option.  Passing cause: true would make the emitted info include the Error.cause property and allow the fullest error logging for users who are using error causes.
I wasn't sure if the conditionals should be `if (cause)` or `if (cause && einfo.cause)`.  I'd be very happy with either.
For background, Error.cause is an ES2022 addition, added to node in 16.9.0.
> Feature - optionally include Error.cause property

- index.d.ts
Being able to use a Symbol as a key for TransformableInfo makes it easier to create cleaner transforms.
The current typing forbids this, so this change enables it.
> TransformableInfo should support symbols as keys

- package-lock.json
- package.json
Simple solution to #242 : Mark the types we use as dependency.
simply running `npm i @types/triple-beam` in any of my failed projects fixes it.
> fix: expose types dependency we depend on

- examples/mask.js
Including a formatting example for masking data with a common use case of customizing how many characters to mask and the character to use for replacing.
Very dependent on particular object property key names, but could possibly be combined with regex expressions for common PII/PCI/PHI data formats.
Inspired by [feature request 2116](https://github.com/winstonjs/winston/issues/2116) from winstonjs/winston.
> Adding mask formatting example

- index.d.ts
The colorize format supports passing in arrays of colors/styles for individual colors. The typescript needs to be updated to match the code.
> Update index.d.ts to support multiple color entries

- index.d.ts
In TS, the `any` type interferes with normal type inference. It's also potentially dangerous, so I recommend using `unknown`. We have changed the type `any` in the `index.d.ts` file to `unknown` to improve the type stability of the library usage.
> refactor: remove any in index.d.ts

- index.d.ts
- package-lock.json
- package.json
Allow creating json formatter with function passed as deterministic comparator.
---
- Improve typing of `JsonOptions.deterministic` to reflect underlying type and allow passing in the comparator.
- Bump `safe-stable-stringify` to latest version explicitly (`deterministic` option supported from 2.5.0 ([ref](https://github.com/BridgeAR/safe-stable-stringify/releases))
Note: With previous `package.json` version selector `^2.3.1` we were installing version `2.5.0` anyway, so the bump in package.json is just to make this explicit.
> fix: Update index.d.ts to improve JsonOptions.deterministic typing
